
### Get all
GET http://localhost:8081/api/cyclists/ HTTP/1.1



### Get 1
GET http://localhost:8081/api/cyclists/laurent HTTP/1.1


### Create
POST http://localhost:8081/api/cyclists/add
Content-Type: application/json
# El body - hi ha d'haver un espai a sota

{
    "name": "pepito",
    "birth_date": "01/01/1962",
    "height": 159, 
    "weight": 55
}

### PENDENT EL DE SOTA 
### PENDENT EL DE SOTA 
### PENDENT EL DE SOTA 
### PENDENT EL DE SOTA 
### PENDENT EL DE SOTA 


### Substitutes all fields by those specified
PUT http://localhost:3000/posts/2
Content-Type: application/json
# El body - hi ha d'haver un espai a sota

{
    "title": "nou title"   
}



### Update only the fields specified
PATCH http://localhost:3000/posts/2
Content-Type: application/json
# El body - hi ha d'haver un espai a sota

{
    "description": "nova descripcio ha estat canviada"   
}


### Delete
DELETE http://localhost:3000/posts/3